on: [ push, pull_request ]

jobs:
  vmo_deployment_keys_demo:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      -   uses: actions/checkout@v3
      -   run: apt update && apt install -y openssh-client git curl
      -   if: ${{ env.ACT }}
          name: Hack container for local development
          run: |
            curl -fsSL https://deb.nodesource.com/setup_16.x | bash -s
            apt-get install -y nodejs
      -   name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'
      -   name: Setup key
          uses: ./
          with:
            ssh-private-keys: |
              {
                "git@github.com:vaimo/vsf2_ext-lru-cache-driver.git": "${{ secrets.TEST_1_DEPLOY_KEY }}",
                "git@github.com:mpdude/test-2.git": "${{ secrets.TEST_2_DEPLOY_KEY }}"
              }
      -   run: |
            git clone https://github.com/vaimo/vsf2_ext-lru-cache-driver.git test-1-http
            git clone git@github.com:vaimo/vsf2_ext-lru-cache-driver.git test-1-git
            git clone ssh://git@github.com/vaimo/vsf2_ext-lru-cache-driver.git test-1-git-ssh
