on: [ push, pull_request ]

jobs:
  vmo_deployment_keys_demo:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install openssh
        run: which openssh-client || (apt-get update && apt-get install -y openssh-client git > /dev/null)
      -   uses: actions/checkout@v3
      -   name: Setup key
          uses: ./
          with:
            ssh-private-keys: |
              [
                {
                  "name": "git@github.com:vaimo/vsf2_ext-lru-cache-driver.git",
                  "key": "${{ secrets.TEST_1_DEPLOY_KEY }}"
                },
                {
                  "name": "git@github.com:mpdude/test-2.git",
                  "key": "${{ secrets.TEST_2_DEPLOY_KEY }}"
                }
              ]
      -   run: |
            git clone https://github.com/vaimo/vsf2_ext-lru-cache-driver.git test-1-http
            git clone git@github.com:vaimo/vsf2_ext-lru-cache-driver.git test-1-git
            git clone ssh://git@github.com/vaimo/vsf2_ext-lru-cache-driver.git test-1-git-ssh
